name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 18 1,10,15,25 * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install axios
        run: npm ci
      - name: Fetch posts
        run: node scripts/news.js
        env:
          URL: '${{secrets.URL}}'
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@greywasp	"
